backend:
  name: git-gateway
  branch: master
  squash_merges: true

local_backend: true

publish_mode: editorial_workflow
#media_folder: images # required but unused, host images externally

media_library:
  name: cloudinary
  config:
    cloud_name: skystone
    api_key: 593158426644373

collections:
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'source/_data/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Google Analytics (eg. UA-XXXXX-Y)', name: ga_analytics_id, widget: string }
          - { label: 'Favicon', name: favicon, widget: image, allow_multiple: false }
      - name: 'offices'
        label: 'Offices'
        file: 'source/_data/offices.json'
        description: 'Office Locations'
        widget: list
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Telephone", name: "telephone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
  - label: "Projects"
    name: "projects"
    folder: "source/_projects"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Status", name: "status", widget: "string" }
      - {label: "Sector", name: "sector", collapsed: false, widget: "list" }
      - {label: "Main Image", name: "image", widget: "image", allow_multiple: false, media_library: { config: { multiple: false } } }
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Image Filename", name: "image", widget: "string", required: false}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
